---
title: "lay theories - study 1"
output:
  html_document: default
  pdf_document: default
---
```{r install/load packages,echo=FALSE,include=FALSE}

library("tidyverse") 
library("psych") 
library("lsr") 

```

```{r read in raw data set}

setwd('~/Box Sync/layTheories_altruism/study1')
df = read.csv('layTheories_s1_raw.csv') #raw data frame - temporary
data = df[,c("id","condition")] # clean data frame - for analysis

```

```{r create clean data frame for analysis}

#create averages for perception ratings 

#AVG: altruism ratings
  alt = df[,grep("Alt", names(df))] #get all altruism ratings 
  #DF should contain ncol = 216. Or N = 3 (DVs per V) x 8 (Vs) x 4 (orders) x 2 (cond: motive/outcome) + 3 (DVs per control V) x 8 (Vs)
    ncol(alt) #sanity check
  alt = alt %>% mutate(alt_avg=rowMeans(alt, na.rm = TRUE)) #create new column averaging across them
  data$perceived_alt = alt$alt_avg
  #sanity_check_alt = describe(alt) #check for correct variables

    #AVGS FOR ALL GROUPS BY MOTIVE, PERSON, ACTION (ncol = 72)
    
      #AVG: altruism ratings - motive
      mtvdata = alt[,grep("m_", names(alt))] #get alt ratings of motives
        ncol(mtvdata) #sanity check
      mtvdata = mtvdata %>% mutate(actC_avg_m_alt=rowMeans(mtvdata, na.rm = TRUE)) #create new column averaging across them
      data$actC_avg_m_alt = mtvdata$actC_avg_m_alt #write to main df
  
      #AVG: altruism ratings - person
      psndata = alt[,grep("p_", names(alt))] #get alt ratings of persons
        ncol(psndata) #sanity check
      psndata = psndata %>% mutate(actC_avg_p_alt=rowMeans(psndata, na.rm = TRUE)) #create new column averaging across them
      data$actC_avg_p_alt = psndata$actC_avg_p_alt #write to main df
    
      #AVG: altruism ratings - action
      actdata = alt[,grep("a_", names(alt))] #get alt ratings of actions
      ncol(actdata) #sanity check
      actdata = actdata %>% mutate(actC_avg_a_alt=rowMeans(actdata, na.rm = TRUE)) #create new column averaging across them
      data$actC_avg_a_alt = actdata$actC_avg_a_alt #write to main df

    rm("mtvdata", "psndata", "actdata") #clean up workspace
  
    #AVGS FOR MOTIVES/OUTCOME GROUPS ONLY (ncol = 48)
    
      #AVG: altruism ratings - material 
      mdata = alt[,grep("_m", names(alt))] #get alt ratings of material motives/outcomes
      mdata = mdata[, -grep("actC", colnames(mdata))] #remove motive ratings from control group, which are picked via '_m'
        ncol(mdata) #sanity check
      mdata = mdata %>% mutate(actMO_avg_m_alt=rowMeans(mdata, na.rm = TRUE)) #create new column averaging across them
      data$actMO_avg_m_alt = mdata$actMO_avg_m_alt #write to main df
    
      #AVG: altruism ratings - social
      sdata = alt[,grep("_s", names(alt))] #get alt ratings of social motives/outcomes
        ncol(sdata) #sanity check
      sdata = sdata %>% mutate(actMO_avg_s_alt=rowMeans(sdata, na.rm = TRUE)) #create new column averaging across them
      data$actMO_avg_s_alt = sdata$actMO_avg_s_alt #write to main df
    
      #AVG: altruism ratings - emotional
      edata = alt[,grep("_e", names(alt))] #get alt ratings of emotional motives/outcomes
        ncol(edata) #sanity check
      edata = edata %>% mutate(actMO_avg_e_alt=rowMeans(edata, na.rm = TRUE)) #create new column averaging across them
      data$actMO_avg_e_alt = edata$actMO_avg_e_alt #write to main df
    
      #AVG: altruism ratings - other-oriented
      odata = alt[,grep("_o", names(alt))] #get alt ratings of other-oriented motives/outcomes
        ncol(odata) #sanity check
      odata = odata %>% mutate(actMO_avg_o_alt=rowMeans(odata, na.rm = TRUE)) #create new column averaging across them
      data$actMO_avg_o_alt = odata$actMO_avg_o_alt #write to main df
    
    rm("mdata", "sdata", "edata", "odata", "alt") #clean up workspace
    
#########################
  
#AVG: selfishness ratings
    self = df[,grep("Self", names(df))] #get all selfishness ratings 
    #DF should contain ncol = 216. Or N = 3 (DVs per V) x 8 (Vs) x 4 (orders) x 2 (cond: motive/outcome) + 3 (DVs per control V) x 8 (Vs)
      ncol(self) #sanity check
    self = self %>% mutate(self_avg=rowMeans(self, na.rm = TRUE)) #create new column averaging across them
    data$perceived_self = self$self_avg
    #sanity_check_self = describe(self) #check for correct variables 

  
    #AVGS FOR ALL GROUPS BY MOTIVE, PERSON, ACTION (ncol = 72)
    
      #AVG: selfishness ratings - motive
      mtvdata = self[,grep("m_", names(self))] #get self ratings of motives
        ncol(mtvdata) #sanity check
      mtvdata = mtvdata %>% mutate(actC_avg_m_self=rowMeans(mtvdata, na.rm = TRUE)) #create new column averaging across them
      data$actC_avg_m_self = mtvdata$actC_avg_m_self #write to main df
    
      #AVG: selfishness ratings - person
      psndata = self[,grep("p_", names(self))] #get self ratings of persons
        ncol(psndata) #sanity check
      psndata = psndata %>% mutate(actC_avg_p_self=rowMeans(psndata, na.rm = TRUE)) #create new column averaging across them
      data$actC_avg_p_self = psndata$actC_avg_p_self #write to main df
    
      #AVG: selfishness ratings - action
      actdata = self[,grep("a_", names(self))] #get self ratings of actions
        ncol(actdata) #sanity check
      actdata = actdata %>% mutate(actC_avg_a_self=rowMeans(actdata, na.rm = TRUE)) #create new column averaging across them
      data$actC_avg_a_self = actdata$actC_avg_a_self #write to main df
    
    rm("mtvdata", "psndata", "actdata") #clean up workspace
  
    #AVGS FOR MOTIVES/OUTCOME GROUPS ONLY (ncol = 48)
  
      #AVG: selfishness ratings - material
      mdata = self[,grep("_m", names(self))] #get self ratings of material motives/outcomes
      mdata = mdata[, -grep("actC", colnames(mdata))] #remove motive ratings from control group, which are picked via '_m' 
      #the above was not an issue for 'e', 's', or 'o'
        ncol(mdata) #sanity check
      mdata = mdata %>% mutate(actMO_avg_m_self=rowMeans(mdata, na.rm = TRUE)) #create new column averaging across them
      data$actMO_avg_m_self = mdata$actMO_avg_m_self #write to main df
    
      #AVG: selfishness ratings - social
      sdata = self[,grep("_s", names(self))] #get self ratings of social motives/outcomes
        ncol(sdata) #sanity check
      sdata = sdata %>% mutate(actMO_avg_s_self=rowMeans(sdata, na.rm = TRUE)) #create new column averaging across them
      data$actMO_avg_s_self = sdata$actMO_avg_s_self #write to main df
    
      #AVG: selfishness ratings - emotional
      edata = self[,grep("_e", names(self))] #get self ratings of emotional motives/outcomes
        ncol(edata) #sanity check
      edata = edata %>% mutate(actMO_avg_e_self=rowMeans(edata, na.rm = TRUE)) #create new column averaging across them
      data$actMO_avg_e_self = edata$actMO_avg_e_self #write to main df
    
      #AVG: selfishness ratings - other-oriented
      odata = self[,grep("_o", names(self))] #get self ratings of other-oriented motives/outcomes
        ncol(odata) #sanity check
      odata = odata %>% mutate(actMO_avg_o_self=rowMeans(odata, na.rm = TRUE)) #create new column averaging across them
      data$actMO_avg_o_self = odata$actMO_avg_o_self #write to main df
    
    rm("mdata", "sdata", "edata", "odata", "self") #clean up workspace
    
```

```{r exclusions}

#create average reading time to exclude those who did not read the prosocial scenarios
  rt = df[,grep("rt", names(df))] #get variables containing time
  ncol(rt) #should be 72. 8 (DVs per 2) x 1 (Cond: Control) + (8 (Vs) x 4 (orders) x 2 (cond: motive/outcome))
  rt = rt %>% mutate(rt_avg=rowMeans(rt, na.rm = TRUE)) #create new column called 'avg' averaging across them
  data$rt = rt$rt_avg
  rm("rt", "df")

  threshold = 1.5  # minimum RT required to read vignettes
  removedRT = subset(data, rt < threshold)  # Ps removed for falling below min avg RT
  data = subset(data, rt >= threshold)  # new dataset, with people below minimum RT removed

plyr::count(data$condition) # participants per condition
  # 1 = control
  # 2 = motive
  # 3 = outcome
```

```{r data reduction & validation,warning=FALSE}

#internal validity
  validity = data[c("actC_avg_a_alt","actC_avg_a_self","actC_avg_m_alt",	"actC_avg_m_self","actC_avg_p_alt","actC_avg_p_self")]	
  alpha(validity, keys=c("actC_avg_a_alt","-actC_avg_a_self","actC_avg_m_alt",	"-actC_avg_m_self","actC_avg_p_alt","-actC_avg_p_self"),
        cumulative=FALSE,
        title=NULL, max=10,na.rm = FALSE,
        check.keys=TRUE,n.iter=1,delete=TRUE)

#correlation between for ratings of altruism (and selfishness) for agent's action, agent's motive, and the agent.
  data_reduce_alt = validity[c(1,3,5)]
  reduce_corr_alt = cor(data_reduce_alt)
  round(reduce_corr_alt, 2)

  data_reduce_self = validity[c(2,4,6)]
  reduce_corr_self = cor(data_reduce_self)
  round(reduce_corr_self, 2)


#compute average altruism and selfishness ratings
  data$perceived_alt = (data$actC_avg_a_alt + data$actC_avg_m_alt + data$actC_avg_p_alt)/3
  data$perceived_self = (data$actC_avg_a_self + data$actC_avg_m_self + data$actC_avg_p_self)/3

#collapsing across altruism and selfishness ratings 
  
  #visualize normality of the two composite measures
    qqplot(data$perceived_alt,data$perceived_self)
      #indicates outliers

  #correlation between ratings of altruism and selfishness (non-parametric to prevent bias from outliers)
   cor.test(data$perceived_alt, data$perceived_self, method = "spearman")

#compute average perceived altruism collapsing across all ratings
  data$alt_comp = ((data$perceived_alt - data$perceived_self)/2)
  
#compute average perceived altruism for each benefit-type
  data$alt_comp_e = ((data$actMO_avg_e_alt - data$actMO_avg_e_self)/2)
  data$alt_comp_m = ((data$actMO_avg_m_alt - data$actMO_avg_m_self)/2)
  data$alt_comp_o = ((data$actMO_avg_o_alt - data$actMO_avg_o_self)/2)
  data$alt_comp_s = ((data$actMO_avg_s_alt - data$actMO_avg_s_self)/2)

#compute average perceived altruism collapsing across all ratings
  data$alt_comp = ((data$perceived_alt - data$perceived_self)/2)
  
```

```{r descriptive & inferential statistics}

#MIXED ANOVA:

#we ran a 4 (benefit type: material, social, emotional, & other-oriented) x 2 (framing: motive vs. consequence) mixed ANOVA in SPSS
#this can found in the 'spss' folder, or to generate the spss csv from scatch, use the code below:

#write.csv(data, file = "layTheories_s1_spss.csv") # exported data for SPSS
#remove "NAs" and redundant first row before importing to SPSS
#see files in data folder for syntax and output for SPSS 


#subset data (only CONSEQUENCE group)
data_outcome = subset(data, condition == "3",select = c("alt_comp_m","alt_comp_s","alt_comp_e","alt_comp_o")) 

  #descriptive statistics
  describe(data_outcome)
  #paired samples t-test comparing other-oriented to material
  t.test(data_outcome$alt_comp_o,data_outcome$alt_comp_m, paired=TRUE) 
  cohensD(data_outcome$alt_comp_o,data_outcome$alt_comp_m) 

  #paired samples t-test comparing other-oriented to social
  t.test(data_outcome$alt_comp_o,data_outcome$alt_comp_s, paired=TRUE) 
  cohensD(data_outcome$alt_comp_o,data_outcome$alt_comp_s) 

  #paired samples t-test comparing other-oriented to emotional
  t.test(data_outcome$alt_comp_o,data_outcome$alt_comp_e, paired=TRUE) 
  cohensD(data_outcome$alt_comp_o,data_outcome$alt_comp_e) 


#subset data (only MOTIVE group)
data_motive = subset(data, condition == "2",select = c("alt_comp_m","alt_comp_s","alt_comp_e","alt_comp_o")) 

  #descriptives
  describe(data_motive)

  #paired samples t-test comparing other-oriented to material
  t.test(data_motive$alt_comp_o,data_motive$alt_comp_m, paired=TRUE) 
  cohensD(data_motive$alt_comp_o,data_motive$alt_comp_m) 

  #paired samples t-test comparing other-oriented to social
  t.test(data_motive$alt_comp_o,data_motive$alt_comp_s, paired=TRUE) 
  cohensD(data_motive$alt_comp_o,data_motive$alt_comp_s) 

  #paired samples t-test comparing other-oriented to emotional
  t.test(data_motive$alt_comp_o,data_motive$alt_comp_e, paired=TRUE) 
  cohensD(data_motive$alt_comp_o,data_motive$alt_comp_e) 

  #one sample t-tests comparing social and material motives to the mid-point of the scale
  t.test(data_motive$alt_comp_m,mu=0) 
  t.test(data_motive$alt_comp_s,mu=0) 

  
#subset data (only CONTROL group)
data_control = subset(data, condition == "1", select = c("alt_comp")) 

  #descriptive statistics
  c = describe(data_control)
  c
  
  #one sample t-test comparing perceived altruism in contorl group to the mid-point of the scale
  
t.test(data_control$alt_comp,mu=0) 


```

```{r plot main results: consequence group}

#PLOT: perceived altruism: consequence group

  names(data_outcome) <- c("material","social","emotional","other-oriented")
  data_outcome_long <- gather(data_outcome, consequence, perceived.altruism, "material":"other-oriented", factor_key=TRUE)
  
s1_f1 = ggplot(data_outcome_long,aes(consequence,perceived.altruism,fill=consequence))+
    stat_summary(geom = "bar",fun.y = "mean",width=.7,alpha=.8)+
    stat_summary(geom = "errorbar",width=.1,color="black",fun.data = "mean_cl_boot")+theme_classic()+
    expand_limits(y=c(-2,4.5))+
    ylab("perceived altruism")+
    geom_hline(aes(yintercept= c$mean, linetype = "control"), colour= 'black') +
    geom_hline(aes(yintercept= 0), colour= 'grey',alpha=.5) +
    scale_linetype_manual(name = "reference", values = c(2, 3))+
    guides(fill = guide_legend(order = 1),color = guide_legend(order = 1))+
    theme(axis.line.y = element_line(color="grey"),
      axis.ticks.y=element_line(color="grey"),
      axis.line.x=element_blank(),
      axis.title.x=element_blank(),
      axis.text.x=element_blank(),
      axis.ticks.x=element_blank())+theme(aspect.ratio=4/3.5)+
    scale_fill_manual("consequence", values = 
                        c("material" = "mediumseagreen", 
                          "social" = "cornflowerblue", 
                          "emotional" = "orange",
                          "other-oriented" = "white"))+
    stat_summary(geom = "bar",fun.y = "mean",width=.7,alpha=0, size=.4, color="black") 

s1_f1
    #ggsave(s1_f1,file='~/s1_f1.pdf')

```

```{r plot main results: motive group}

#PLOT: perceived altruism: motive group
  
  names(data_motive) <- c("material","social","emotional","other-oriented")
  data_motive_long <- gather(data_motive, motive, perceived.altruism, "material":"other-oriented",factor_key = TRUE)

s1_f2 = ggplot(data_motive_long,aes(motive,perceived.altruism,fill=motive))+
    stat_summary(geom = "bar",fun.y = "mean",width=.7,alpha=.8)+
    stat_summary(geom = "errorbar",width=.1,color="black",fun.data = "mean_cl_boot")+theme_classic()+
    expand_limits(y=c(-2,4.5))+
    ylab("perceived altruism")+
    geom_hline(aes(yintercept= c$mean, linetype = "control"), colour= 'black') +
    geom_hline(aes(yintercept= 0), colour= 'grey',alpha=.5) +
    scale_linetype_manual(name = "reference", values = c(2, 3))+
    guides(fill = guide_legend(order = 1),color = guide_legend(order = 1))+
    theme(axis.line.y = element_line(color="grey"),
      axis.ticks.y=element_line(color="grey"),
      axis.line.x=element_blank(),
      axis.title.x=element_blank(),
      axis.text.x=element_blank(),
      axis.ticks.x=element_blank())+theme(aspect.ratio=4/3.5)+
    scale_fill_manual("motive", values = 
                        c("material" = "mediumseagreen", 
                          "social" = "cornflowerblue", 
                          "emotional" = "orange",
                          "other-oriented" = "white"))+
    stat_summary(geom = "bar",fun.y = "mean",width=.7,alpha=0, size=.4, color="black") 

s1_f2
    #ggsave(s1_f2,file='~/s1_f2.pdf')

```

```{r supplemental analysis: seperately analysing altruism and selfishness ratings}

#we ran a 4 (benefit type: material, social, emotional, & other-oriented) x 2 (framing: motive vs. consequence) mixed ANOVA in SPSS
#see supplementary files in data folder for syntax and output for SPSS 

#SELFISHNESS RATINGS

#subset data (only CONSEQUENCE group)
supp_data_outcome = subset(data, condition == "3",select = c("actMO_avg_m_self","actMO_avg_s_self","actMO_avg_e_self","actMO_avg_o_self"))

  #descriptive statistics
  describe(supp_data_outcome)

  #paired samples t-test comparing other-oriented to material
  t.test(supp_data_outcome$actMO_avg_o_self,
         supp_data_outcome$actMO_avg_m_self, paired=TRUE) 
  cohensD(supp_data_outcome$actMO_avg_o_self,
          supp_data_outcome$actMO_avg_m_self) 

  #paired samples t-test comparing other-oriented to social
  t.test(supp_data_outcome$actMO_avg_o_self, 
         supp_data_outcome$actMO_avg_s_self, paired=TRUE) 
  cohensD(supp_data_outcome$actMO_avg_o_self,
          supp_data_outcome$actMO_avg_s_self) 

  #paired samples t-test comparing other-oriented to emotional
  t.test(supp_data_outcome$actMO_avg_o_self,
        supp_data_outcome$actMO_avg_e_self, paired=TRUE) 
  cohensD(supp_data_outcome$actMO_avg_o_self,
          supp_data_outcome$actMO_avg_e_self) 

#subset data (only MOTIVE group)
supp_data_motive = subset(data, condition == "2",select = c("actMO_avg_m_self","actMO_avg_s_self","actMO_avg_e_self","actMO_avg_o_self")) 

  #descriptives
  describe(supp_data_motive)

  #paired samples t-test comparing other-oriented to material
  t.test(supp_data_motive$actMO_avg_o_self,
         supp_data_motive$actMO_avg_m_self, paired=TRUE) 
  cohensD(supp_data_motive$actMO_avg_o_self,
          supp_data_motive$actMO_avg_m_self) 

  #paired samples t-test comparing other-oriented to social
  t.test(supp_data_motive$actMO_avg_o_self,
         supp_data_motive$actMO_avg_s_self, paired=TRUE) 
  cohensD(supp_data_motive$actMO_avg_o_self,
          supp_data_motive$actMO_avg_s_self) 

  #paired samples t-test comparing other-oriented to emotional
 t.test(supp_data_motive$actMO_avg_o_self,
        supp_data_motive$actMO_avg_e_self, paired=TRUE) 
  cohensD(supp_data_motive$actMO_avg_o_self,
          supp_data_motive$actMO_avg_e_self) 
  
#subset data (only CONTROL group)
supp_data_control = subset(data, condition == "1", select = c("perceived_self"))

  #descriptive statistics
  c = describe(supp_data_control)
  c

```

```{r plot supp results: selfishness}

#PLOT: selfishness: consequence group

 names(supp_data_outcome) <- c("material","social","emotional","other-oriented")
 supp_data_outcome_long <- gather(supp_data_outcome, consequence, selfishness, "material":"other-oriented", factor_key=TRUE)
      
supp_s1_f1 = ggplot(supp_data_outcome_long,aes(consequence,selfishness,fill=consequence))+
    stat_summary(geom = "bar",fun.y = "mean",width=.7,alpha=.8)+
    stat_summary(geom = "errorbar",width=.1,color="black",fun.data = "mean_cl_boot")+theme_classic()+
    expand_limits(y=c(0,8))+
    ylab("selfishness")+
    geom_hline(aes(yintercept= c$mean, linetype = "control"), colour= 'black') +
    geom_hline(aes(yintercept= 0), colour= 'grey',alpha=.5) +
    scale_linetype_manual(name = "reference", values = c(2, 3))+
    guides(fill = guide_legend(order = 1),color = guide_legend(order = 1))+
    theme(axis.line.y = element_line(color="grey"),
      axis.ticks.y=element_line(color="grey"),
      axis.line.x=element_blank(),
      axis.title.x=element_blank(),
      axis.text.x=element_blank(),
      axis.ticks.x=element_blank())+theme(aspect.ratio=4/3.5)+
    scale_fill_manual("consequence", values = 
                        c("material" = "mediumseagreen", 
                          "social" = "cornflowerblue", 
                          "emotional" = "orange",
                          "other-oriented" = "white"))+
    stat_summary(geom = "bar",fun.y = "mean",width=.7,alpha=0, size=.4, color="black")

supp_s1_f1 
    #ggsave(supp_s1_f1,file='~/supp_s1_f1.pdf')

  
#PLOT: selfishness: motive group
  
  names(supp_data_motive) <- c("material","social","emotional","other-oriented")
  supp_data_motive_long <- gather(supp_data_motive, motive, selfishness, "material":"other-oriented",factor_key = TRUE)

supp_s1_f2 = ggplot(supp_data_motive_long,aes(motive,selfishness,fill=motive))+
    stat_summary(geom = "bar",fun.y = "mean",width=.7,alpha=.8)+
    stat_summary(geom = "errorbar",width=.1,color="black",fun.data = "mean_cl_boot")+theme_classic()+
    expand_limits(y=c(0,8))+
    ylab("selfishness")+
    geom_hline(aes(yintercept= c$mean, linetype = "control"), colour= 'black') +
    geom_hline(aes(yintercept= 0), colour= 'grey',alpha=.5) +
    scale_linetype_manual(name = "reference", values = c(2, 3))+
    guides(fill = guide_legend(order = 1),color = guide_legend(order = 1))+
    theme(axis.line.y = element_line(color="grey"),
      axis.ticks.y=element_line(color="grey"),
      axis.line.x=element_blank(),
      axis.title.x=element_blank(),
      axis.text.x=element_blank(),
      axis.ticks.x=element_blank())+theme(aspect.ratio=4/3.5)+
    scale_fill_manual("motive", values = 
                        c("material" = "mediumseagreen", 
                          "social" = "cornflowerblue", 
                          "emotional" = "orange",
                          "other-oriented" = "white"))+
    stat_summary(geom = "bar",fun.y = "mean",width=.7,alpha=0, size=.4, color="black")

supp_s1_f2 
    #ggsave(supp_s1_f2,file='~/supp_s1_f2.pdf')

```

```{r supplemental analysis2: seperately analysing altruism and selfishness ratings}

#ALTRUISM RATINGS

#subset data (only CONSEQUENCE group)
supp_data_outcome = subset(data, condition == "3",select = c("actMO_avg_m_alt","actMO_avg_s_alt","actMO_avg_e_alt","actMO_avg_o_alt"))

  #descriptive statistics
  describe(supp_data_outcome)

  #paired samples t-test comparing other-oriented to material
  t.test(supp_data_outcome$actMO_avg_o_alt,
         supp_data_outcome$actMO_avg_m_alt, paired=TRUE) 
  cohensD(supp_data_outcome$actMO_avg_o_alt,
          supp_data_outcome$actMO_avg_m_alt) 

  #paired samples t-test comparing other-oriented to social
  t.test(supp_data_outcome$actMO_avg_o_alt,
         supp_data_outcome$actMO_avg_s_alt, paired=TRUE) 
  cohensD(supp_data_outcome$actMO_avg_o_alt,
          supp_data_outcome$actMO_avg_s_alt) 

  #paired samples t-test comparing other-oriented to emotional
   t.test(supp_data_outcome$actMO_avg_o_alt,
          supp_data_outcome$actMO_avg_e_alt, paired=TRUE) 
  cohensD(supp_data_outcome$actMO_avg_o_alt,
          supp_data_outcome$actMO_avg_e_alt) 

#subset data (only MOTIVE group)
supp_data_motive = subset(data, condition == "2",select = c("actMO_avg_m_alt","actMO_avg_s_alt","actMO_avg_e_alt","actMO_avg_o_alt")) 

  #descriptives
  describe(supp_data_motive)

  #paired samples t-test comparing other-oriented to material
  t.test(supp_data_motive$actMO_avg_o_alt,
         supp_data_motive$actMO_avg_m_alt, paired=TRUE) 
  cohensD(supp_data_motive$actMO_avg_o_alt,
          supp_data_motive$actMO_avg_m_alt) 

  #paired samples t-test comparing other-oriented to social
  t.test(supp_data_motive$actMO_avg_o_alt,
         supp_data_motive$actMO_avg_s_alt, paired=TRUE) 
  cohensD(supp_data_motive$actMO_avg_o_alt,
          supp_data_motive$actMO_avg_s_alt) 

  #paired samples t-test comparing other-oriented to emotional
  t.test(supp_data_motive$actMO_avg_o_alt,
        supp_data_motive$actMO_avg_e_alt, paired=TRUE) 
  cohensD(supp_data_motive$actMO_avg_o_alt,
          supp_data_motive$actMO_avg_e_alt)  
  
#subset data (only CONTROL group)
supp_data_control = subset(data, condition == "1", select = c("perceived_alt"))

  #descriptive statistics
  c = describe(supp_data_control)
  c
  
```

```{r plot supp results: altruism}
 
#PLOT: altruism: consequence group
 
 names(supp_data_outcome) <- c("material","social","emotional","other-oriented")
 supp_data_outcome_long <- gather(supp_data_outcome, consequence, altruism, "material":"other-oriented", factor_key=TRUE)
      
supp_s1_f3 = ggplot(supp_data_outcome_long,aes(consequence,altruism,fill=consequence))+
    stat_summary(geom = "bar",fun.y = "mean",width=.7,alpha=.8)+
    stat_summary(geom = "errorbar",width=.1,color="black",fun.data = "mean_cl_boot")+theme_classic()+
    expand_limits(y=c(0,8))+
    ylab("altruism")+
    geom_hline(aes(yintercept= c$mean, linetype = "control"), colour= 'black') +
    geom_hline(aes(yintercept= 0), colour= 'grey',alpha=.5) +
    scale_linetype_manual(name = "reference", values = c(2, 3))+
    guides(fill = guide_legend(order = 1),color = guide_legend(order = 1))+
    theme(axis.line.y = element_line(color="grey"),
      axis.ticks.y=element_line(color="grey"),
      axis.line.x=element_blank(),
      axis.title.x=element_blank(),
      axis.text.x=element_blank(),
      axis.ticks.x=element_blank())+theme(aspect.ratio=4/3.5)+
    scale_fill_manual("consequence", values = 
                        c("material" = "mediumseagreen", 
                          "social" = "cornflowerblue", 
                          "emotional" = "orange",
                          "other-oriented" = "white"))+
    stat_summary(geom = "bar",fun.y = "mean",width=.7,alpha=0, size=.4, color="black")

supp_s1_f3 
    #ggsave(supp_s1_f3,file='~/supp_s1_f3.pdf')


#PLOT: altruism: motive group
  
  names(supp_data_motive) <- c("material","social","emotional","other-oriented")
  supp_data_motive_long <- gather(supp_data_motive, motive, altruism, "material":"other-oriented",factor_key = TRUE)

supp_s1_f4 = ggplot(supp_data_motive_long,aes(motive,altruism,fill=motive))+
    stat_summary(geom = "bar",fun.y = "mean",width=.7,alpha=.8)+
    stat_summary(geom = "errorbar",width=.1,color="black",fun.data = "mean_cl_boot")+theme_classic()+
    expand_limits(y=c(0,8))+
    ylab("altruism")+
    geom_hline(aes(yintercept= c$mean, linetype = "control"), colour= 'black') +
    geom_hline(aes(yintercept= 0), colour= 'grey',alpha=.5) +
    scale_linetype_manual(name = "reference", values = c(2, 3))+
    guides(fill = guide_legend(order = 1),color = guide_legend(order = 1))+
    theme(axis.line.y = element_line(color="grey"),
      axis.ticks.y=element_line(color="grey"),
      axis.line.x=element_blank(),
      axis.title.x=element_blank(),
      axis.text.x=element_blank(),
      axis.ticks.x=element_blank())+theme(aspect.ratio=4/3.5)+
    scale_fill_manual("motive", values = 
                        c("material" = "mediumseagreen", 
                          "social" = "cornflowerblue", 
                          "emotional" = "orange",
                          "other-oriented" = "white"))+
    stat_summary(geom = "bar",fun.y = "mean",width=.7,alpha=0, size=.4, color="black")

supp_s1_f4 
    #ggsave(supp_s1_f4,file='~/supp_s1_f4.pdf')
  
  
```
